language: generic
sudo: required
services:
  - docker

# before_install:
#   - docker build -t acasado86/angular-test -f ./ng-client/Dockerfile.dev ./ng-client
#   - docker build -t acasado86/react-test -f ./client/Dockerfile.dev ./client

# script:
#   - docker run acasado86/angular-test npm run test
#   - docker run -e CI=true acasado86/react-test npm run test -- --coverage

after_succes:
  - docker build --build-arg PUBLIC_URL=/react -t acasado86/multi-client ./client
  # - docker build -t acasado86/multi-ng-client ./ng-client
  - docker build -t acasado86/multi-nginx ./nginx
  # - docker build -t acasado86/multi-server ./server
  # - docker build -t acasado86/multi-worker ./worker
  # # Log in to the docker CLI
  # - echo "$DOCKER_PASS" | docker login --username "$DOCKER_ID" --password-stdin
  # # Take those images and push to docker hub
  - docker push acasado86/multi-client
  # - docker push acasado86/multi-ng-client
  - docker push acasado86/multi-nginx
  # - docker push acasado86/multi-server
  # - docker push acasado86/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-west-3'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-eu-west-3-364567996486'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY