language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t acasado/angular-test -f ./ng-client/Dockerfile.dev ./ng-client
  - docker build -t acasado/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run acasado/angular-test npm run test
  - docker run -e CI=true acasado/react-test npm run test -- --coverage

after_succes:
  - docker build --build-arg PUBLIC_URL=/react -t acasado/multi-client ./client
  - docker build -t acasado/multi-ng-client ./ng-client
  - docker build -t acasado/multi-nginx ./nginx
  - docker build -t acasado/multi-server ./server
  - docker build -t acasado/multi-worker ./worker