version: '3.1'
services: 
    postgres:
        image: 'postgres:latest'
        restart: always
        environment:
            POSTGRES_PASSWORD: example
    redis:
        image: 'redis:latest'
    nginx:
        depends_on:
            - api
            - client
            - ng-client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - "80:80"
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
            PGUSER: postgres
            PGHOST: postgres
            PGBATABASE: postgres
            PGPASSWORD: example
            PGPORT: 5432
    worker:
        build:
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes:
            - /app/node_modules
            - ./worker:/app
        environment:
            REDIS_HOST: redis
            REDIS_PORT: 6379
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app
    ng-client:
        # ports:
        #     - "4200:4200"
        build:
            dockerfile: Dockerfile.dev
            context: ./ng-client
        volumes:
            - /app/node_modules
            - ./ng-client:/app